version: '3.8'

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: social_network
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - master_data:/var/lib/mysql
      - ./sql/replication/master.cnf:/etc/mysql/conf.d/master.cnf
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
      - ./sql/replication/create-replication-user.sql:/docker-entrypoint-initdb.d/3-create-replication-user.sql
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mysql-replica:
    image: mysql:8.0
    container_name: mysql-replica
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - replica_data:/var/lib/mysql
      - ./sql/replication/replica.cnf:/etc/mysql/conf.d/replica.cnf
    networks:
      - db_network
    depends_on:
      mysql-master:
        condition: service_healthy

  backend:
    build: ./backend
    container_name: social-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MASTER_DB_HOST=mysql-master
      - MASTER_DB_PORT=3306
      - MASTER_DB_USER=app_user
      - MASTER_DB_PASSWORD=app_password
      - MASTER_DB_NAME=social_network
      - REPLICA_DB_HOST=mysql-replica
      - REPLICA_DB_PORT=3306
      - REPLICA_DB_USER=app_user
      - REPLICA_DB_PASSWORD=app_password
      - REPLICA_DB_NAME=social_network
    networks:
      - db_network
    depends_on:
      - mysql-master
      - mysql-replica

networks:
  db_network:
    driver: bridge

volumes:
  master_data:
  replica_data:
